### ISSUE TITLE
can't work with TestServer when UseMetricsReporting(lifetime)

### ISSUE THREAD

**Issue by vinhhrv** [alhardy/AppMetrics.Extensions.InfluxDB#4]
```
public class UnitTest1
    {
        private readonly TestServer _server;
        public readonly HttpClient _client;

        public UnitTest1()
        {
            _server = new TestServer(new WebHostBuilder()
                                .UseStartup<Startup>());
            _client = _server.CreateClient();
        }
        [Fact]
        public void Test1()
        {
        }
    }
```

I use your sample Api.InfluxDB.Sample
Add XUnitTest project
Try unit test above
can't work

Try comment this
//app.UseMetricsReporting(lifetime);
=> Work

Thank for you lib, it very usefull

**Comment by alhardy** [comment]
@vinhhrv Glad you find it useful.

I'm not sure but I'd say it's probably something to do with the `IApplicationLifetime`, where are you getting that instance from? Maybe you can mock that?

**Comment by vinhhrv** [comment]
@alhardy
Your sample
![image](https://cloud.githubusercontent.com/assets/769541/25217001/76a57c98-25cf-11e7-9fd9-74a4260ec54e.png)

My UnitTest

![image](https://cloud.githubusercontent.com/assets/769541/25217042/8f052068-25cf-11e7-838d-5506fd4b8c5f.png)

**Comment by alhardy** [comment]
OK I found the project, when run in a unit test when is the `ApplicationLifetime.ApplicationStopping` token expected to be stopped? In my test the token is never cancelled so the reporter continues to run.

For your tests are you able to just use a test startup to run your `TestServer`? e..g https://github.com/alhardy/AppMetrics/blob/dev/test/App.Metrics.Extensions.Middleware.Integration.Facts/Startup/DefaultTestStartup.cs Alternatively, have the cancellation token on the `IApplicationLifetime` cancelled after your test run.

**Comment by vinhhrv** [comment]
@alhardy 

When i use UseMetricsReporting

IApplicationLifetime 

appLifetime.ApplicationStarted.Register(() => 
{
 });

Not Work, issue is criticle, please fix

**Comment by alhardy** [comment]
@vinhhrv can you provide some more details please? If possible a sample or unit test, otherwise what exactly isn't working and what are you trying to achieve.

**Comment by vinhhrv** [comment]
Unit Test For Can't Start with Test Server

[XUnitTest_AppMetric.zip](https://github.com/alhardy/AppMetrics.Extensions.InfluxDB/files/949412/XUnitTest_AppMetric.zip)

When run in real env, application can start, but ApplicationLifetime problem

appLifetime.ApplicationStarted.Register(() =>
{
      // not fire
});

**Comment by alhardy** [comment]
@vinhhrv The `UseMetricsReporting` extension method is registering a delegate on the `IApplicationLIfetime` and therefore will override the delegate you are registering. `UseMetricsReporting` is simply a [helper method](https://github.com/alhardy/AppMetrics/blob/master/src/App.Metrics.Extensions.Middleware/DependencyInjection/AspNetMetricsAppBuilderExtensions.cs#L109) to simplify running a reporter in a web context.

If you require more than just registering a reporter you can implement the same thing yourself, e.g. change your code sample's `Startup_with_reporting` `Configure` method to the following:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime appLifetime)
        {
            var reportFactory = app.ApplicationServices.GetRequiredService<IReportFactory>();
            var metrics = app.ApplicationServices.GetRequiredService<IMetrics>();
            var reporter = reportFactory.CreateReporter();

            appLifetime.ApplicationStarted.Register(
                () =>
                {
                    IsStarted = true;
                    reporter.RunReports(metrics, appLifetime.ApplicationStopping);
                });

            app.UseMetrics();
        }
```

**Comment by vinhhrv** [comment]
appLifetime.ApplicationStarted.Register(
                () =>
                {
                    IsStarted = true;
                    reporter.RunReports(metrics, appLifetime.ApplicationStopping);
                    Console.Write("event one never run");
                });

appLifetime.ApplicationStarted.Register(
                () =>
                {
                    Console.Write("event two never run tow");
                });

this is problem, the code run block here.
 reporter.RunReports(metrics, appLifetime.ApplicationStopping);
this function shoult be async task.

if u remove this line, two event is run

**Comment by alhardy** [comment]
@vinhhrv I see, for now you can just run `reporter.RunReports` in a new `Task`.  `Task.Run(() => ... )`

I'm familiar with FluentScheduler, I don't want to take any other dependencies when they can be avoided, plus that's a bit overkil for my needs.

**Comment by alhardy** [comment]
@vinhhrv  https://github.com/alhardy/AppMetrics/issues/129
