### ISSUE TITLE
Optimize perfs and allocations

### ISSUE THREAD

**Issue by tbolon** [alhardy/AppMetrics.Extensions.InfluxDB#46]
Hi,

We are using AppMetrics to send metrics to InfluxDB.

We have observed some places where performances can be enhanced (mostly regarding allocations).

I have created a branch to add benchmarks on this project (with the same structure as benchmarks in AppMetrics project). It will be used to detect any regression.

You can browse the changes in [my fork](https://github.com/mb3m/InfluxDB/tree/benchmarks).

For now, we have identified: (checked items are already fixed in my branch)

- [X] allocations in MetricSnapshotInfluxDbLineProtocolWriter. Dictionary are created for [each data point](https://github.com/AppMetrics/InfluxDB/blob/dev/src/App.Metrics.Formatters.InfluxDB/MetricSnapshotInfluxDBLineProtocolWriter.cs#L43) and linq is used to [merge field names and values](https://github.com/AppMetrics/InfluxDB/blob/dev/src/App.Metrics.Formatters.InfluxDB/MetricSnapshotInfluxDBLineProtocolWriter.cs#L49). We can easily get rid of any allocation by keeping values passed as parameters.

- [x] allocations in InfluxDbMetricsReporter.FlushAsync. data are written to a memory stream then [converted as a string](https://github.com/AppMetrics/InfluxDB/blob/dev/src/App.Metrics.Reporting.InfluxDB/InfluxDbMetricsReporter.cs#L71) to be written to the http request. We could certainly at least pass directly the stream to the WriteAsync method and prevent a string allocation.

I have kept all previous classes to generate baseline benchmarks.

I tried to made these changes not too disturbing, and prevented code duplication when possible.

Our plan is to reduce further the cost of writing points to prevent as much as possible garbage collection. I hope you will find these change useful. If so, I will create a PR so you could review the changes in detail.

Regards,

**Comment by alhardy** [comment]
@tbolon sorry for the late reply, and thanks for taking the time.

Could you create a pull request please

**Comment by tbolon** [comment]
Yes, I am out of office until March 11th. I will create a PR when back.Thanks!

**Comment by tbolon** [comment]
I have created a PR and updated the issue.

All tests are green, and I will update the issue with a copy of the benchmark results soon.

Edit: you will have to wait tomorrow, since my laptop is not really benchmark friendly (my cpu is throttled) :(
